/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FeToggle {
        "disabled": boolean;
        "isRound": boolean;
        "label": string;
        "name": string;
    }
}
declare global {
    interface HTMLFeToggleElement extends Components.FeToggle, HTMLStencilElement {
    }
    var HTMLFeToggleElement: {
        prototype: HTMLFeToggleElement;
        new (): HTMLFeToggleElement;
    };
    interface HTMLElementTagNameMap {
        "fe-toggle": HTMLFeToggleElement;
    }
}
declare namespace LocalJSX {
    interface FeToggle {
        "disabled"?: boolean;
        "isRound"?: boolean;
        "label"?: string;
        "name"?: string;
        "onOnToggle"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "fe-toggle": FeToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fe-toggle": LocalJSX.FeToggle & JSXBase.HTMLAttributes<HTMLFeToggleElement>;
        }
    }
}
